<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>OSPSuite.FuncParser.Tests</RootNamespace>
    <Configurations>Debug;Release;Purify_Debug</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Appveyor.TestLogger" Version="2.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="OSPSuite.BDDHelper" Version="4.0.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OSPSuite.FuncParser\OSPSuite.FuncParser.csproj" />
  </ItemGroup>
</Project>
