image: 
- Visual Studio 2019
- Ubuntu1804

# hack until donet patching works with PR
init: 
  - cmd: if DEFINED APPVEYOR_PULL_REQUEST_NUMBER (Set build_number=1) ELSE (Set build_number=%APPVEYOR_BUILD_NUMBER%)

environment:
  major: 4
  minor: 0
  release: 0
  app_version: "$(major).$(minor).$(release)"

version: "$(major).$(minor).$(release).{build}"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '$(app_version).$(build_number)'
  file_version: '$(app_version).$(build_number)'
  informational_version: '$(app_version).$(build_number)'

build_script:
  - cmd: msbuild OSPSuite.FuncParser.sln /property:Configuration=Debug;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild OSPSuite.FuncParser.sln /property:Configuration=Release;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # linux specific cmake build of native project FuncParserNative
  - sh: cmake -BBuild/Release/x64/ -Hsrc/OSPSuite.FuncParserNative/ -DCMAKE_BUILD_TYPE=Release
  - sh: cmake -BBuild/Debug/x64/ -Hsrc/OSPSuite.FuncParserNative/ -DCMAKE_BUILD_TYPE=Debug
  - sh: make -C Build/Debug/x64; make -C Build/Release/x64
  - sh: dotnet build OSPSuite.FuncParser.sln /property:Configuration=Debug;Platform=x64
  - sh: dotnet build OSPSuite.FuncParser.sln /property:Configuration=Release;Platform=x64

before_build: 
  - ps: (get-content src\OSPSuite.FuncParserNative\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE $env:RELEASE" -replace "MAJOR 0", "MAJOR $env:MAJOR" -replace "MINOR 0", "MINOR $env:MINOR" -replace "BUILD 0", "BUILD $env:APPVEYOR_BUILD_NUMBER"} | set-content src\OSPSuite.FuncParserNative\version.h
  # linux specific source ordering is important here to make sure that bddhelper is fetched from appveyor and not from nuget.org 
  - dotnet restore --source https://ci.appveyor.com/nuget/ospsuite-utility --source https://ci.appveyor.com/nuget/ospsuite-bddhelper --source https://www.nuget.org/api/v2/
  # linux specific removal of native project FuncParserNative from the solution
  - sh: dotnet sln OSPSuite.FuncParser.sln remove src/OSPSuite.FuncParserNative/OSPSuite.FuncParserNative.vcxproj

after_build:
  - cmd: nuget pack src\OSPSuite.FuncParser\OSPSuite.FuncParser.nuspec -version %app_version%.%build_number%
  - sh: nuget pack src/OSPSuite.FuncParser/OSPSuite.FuncParserUbuntu18.nuspec -version $(app_version).$(build_number)
  - ps: Get-ChildItem .\OSPSuite.FuncParser*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
  - ps: dotnet test --no-build --no-restore --logger:Appveyor --configuration:Release 

skip_branch_with_pr: true

skip_tags: true

skip_commits:
  files:
    - "*.md"

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

#notifications:
#  - provider: Slack
#    incoming_webhook:
#      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=
