image: 
- Visual Studio 2022
- Ubuntu2204
- macOS

environment:
  major: 4
  minor: 0
  release: 0
  app_version: "$(major).$(minor).$(release).$(APPVEYOR_BUILD_NUMBER)"

version: "$(major).$(minor).$(release).{build}"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '$(app_version)'
  file_version: '$(app_version)'
  informational_version: '$(app_version)'

build_script:
  - cmd: msbuild OSPSuite.FuncParser.sln /property:Configuration=Debug;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild OSPSuite.FuncParser.sln /property:Configuration=Release;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # linux specific cmake build of native project FuncParserNative
  - sh: cmake -BBuild/Release/x64/ -Hsrc/OSPSuite.FuncParserNative/ -DCMAKE_BUILD_TYPE=Release
  - sh: cmake -BBuild/Debug/x64/ -Hsrc/OSPSuite.FuncParserNative/ -DCMAKE_BUILD_TYPE=Debug
  - sh: make -C Build/Debug/x64; make -C Build/Release/x64
  - sh: dotnet build OSPSuite.FuncParser.sln /property:Configuration=Debug;Platform=x64
  - sh: dotnet build OSPSuite.FuncParser.sln /property:Configuration=Release;Platform=x64

before_build: 
  - ps: (get-content src\OSPSuite.FuncParserNative\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE $env:RELEASE" -replace "MAJOR 0", "MAJOR $env:MAJOR" -replace "MINOR 0", "MINOR $env:MINOR" -replace "BUILD 0", "BUILD $env:APPVEYOR_BUILD_NUMBER"} | set-content src\OSPSuite.FuncParserNative\version.h
  # linux specific source ordering is important here to make sure that bddhelper is fetched from appveyor and not from nuget.org 
  - dotnet restore --source https://ci.appveyor.com/nuget/ospsuite-utility --source https://ci.appveyor.com/nuget/ospsuite-bddhelper --source https://www.nuget.org/api/v2/
  # linux specific removal of native project FuncParserNative from the solution
  - sh: dotnet sln OSPSuite.FuncParser.sln remove src/OSPSuite.FuncParserNative/OSPSuite.FuncParserNative.vcxproj

after_build:
  - cmd: dotnet pack src/OSPSuite.FuncParser/ -p:PackageVersion=%app_version%
  - sh: dotnet pack src/OSPSuite.FuncParser/ -p:PackageVersion=%app_version%
  - ps: Get-ChildItem .\OSPSuite.FuncParser*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
  - ps: dotnet test --no-build --no-restore --logger:Appveyor --configuration:Release 

skip_branch_with_pr: true

skip_tags: true

skip_commits:
  files:
    - "*.md"

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true
