name: Build PR for all supported platforms

on:
  pull_request:
    branches:
    - master

permissions:
  packages: read
  contents: read

env:
  MAJOR: 5
  MINOR: 0
  RELEASE: 0
  RUN: ${{ github.run_number }}

jobs:
  build-nix:
    strategy:
      matrix:
        include:
          - os: ${{ vars.GHA_DEFAULT_RUNNER_MACOS }}
            platform: MacOS
            version_h_modifier: "sed -i ''"
          - os: ubuntu-22.04
            platform: ${{ vars.GHA_DEFAULT_RUNNER_UBUNTU }}
            version_h_modifier: "sed -i"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          echo "BUILD_ID=999${{ env.RUN }}" >> $GITHUB_ENV
          echo "APP_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.RELEASE }}.999${{ env.RUN }}" >> $GITHUB_ENV

      - name: Update version.h
        run: |
          LC_ALL=C ${{ matrix.version_h_modifier }} -e "s@RELEASE 0@RELEASE ${{env.RELEASE}}@g" \
              -e "s@MAJOR 0@MAJOR ${{env.MAJOR}}@g" \
              -e "s@MINOR 0@MINOR ${{env.MINOR}}@g" \
              -e "s@BUILD 0@BUILD ${{ env.BUILD_ID }}@g" \
              src/OSPSuite.FuncParserNative/version.h

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Add OSP NuGet Source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"  --name OSP-GitHub-Packages --username Open-Systems-Pharmacology --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Build Debug and Release
        run: ./buildNix.sh ${{matrix.platform}}  ${{env.APP_VERSION}}

      - name: Push test log as artifact
        uses: actions/upload-artifact@v7
        with:
          name: testLog_${{matrix.os}}
          path: ./**/testLog*.html

  build-windows-x64:
    runs-on: ${{ vars.GHA_DEFAULT_RUNNER_WINDOWS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          echo "BUILD_ID=999${{ env.RUN }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "APP_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.RELEASE }}.999${{ env.RUN }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Add OSP NuGet Source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"  --name OSP-GitHub-Packages --username Open-Systems-Pharmacology --password ${{ secrets.GITHUB_TOKEN }}

      - name: Update version.h
        shell: pwsh
        run: |
          (get-content src\OSPSuite.FuncParserNative\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE ${{env.RELEASE}}" -replace "MAJOR 0", "MAJOR ${{env.MAJOR}}" -replace "MINOR 0", "MINOR ${{env.MINOR}}" -replace "BUILD 0", "BUILD ${{ env.BUILD_ID }}" } | set-content src\OSPSuite.FuncParserNative\version.h

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build native (Release)
        run: msbuild src\OSPSuite.FuncParserNative\OSPSuite.FuncParserNative.vcxproj /p:Configuration=Release /p:Platform=x64 /p:SolutionDir=${{ github.workspace }}\

      - name: Build native (Debug)
        run: msbuild src\OSPSuite.FuncParserNative\OSPSuite.FuncParserNative.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:SolutionDir=${{ github.workspace }}\

      - name: Create .NET-only solution
        shell: pwsh
        run: |
          Copy-Item OSPSuite.FuncParser.sln OSPSuite.FuncParser.NetOnly.sln
          dotnet sln OSPSuite.FuncParser.NetOnly.sln remove src\OSPSuite.FuncParserNative\OSPSuite.FuncParserNative.vcxproj

      - name: Restore .NET projects
        run: dotnet restore OSPSuite.FuncParser.NetOnly.sln

      - name: Build managed (Release)
        run: dotnet build OSPSuite.FuncParser.NetOnly.sln --configuration Release --no-restore

      - name: Build managed (Debug)
        run: dotnet build OSPSuite.FuncParser.NetOnly.sln --configuration Debug --no-restore

      - name: Test
        run: dotnet test OSPSuite.FuncParser.NetOnly.sln --no-build --no-restore --configuration Release --logger:"html;LogFileName=../../../testLog_Windows.html"

      - name: Pack the project
        run: dotnet pack src/OSPSuite.FuncParser/ -o ./ -p:PackageVersion=${{env.APP_VERSION}} --no-build --no-restore --configuration Release

      - name: Push test log as artifact
        uses: actions/upload-artifact@v7
        with:
          name: testLog_Windows
          path: ./**/testLog*.html
