name: Build PR for all supported platforms

on:
  pull_request:
    branches:
    - master

permissions:
  packages: read
  contents: read

env:
  MAJOR: 5
  MINOR: 0
  RELEASE: 0
  RUN: ${{ github.run_number }}

jobs:
  build-nix-matrix:
    strategy:
      matrix:
        include:
          - os: ${{ vars.GHA_DEFAULT_RUNNER_MACOS }}
            platform: MacOS
            version_h_modifier: "sed -i ''"
          - os: ubuntu-22.04
            platform: ${{ vars.GHA_DEFAULT_RUNNER_UBUNTU }}
            version_h_modifier: "sed -i"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          echo "BUILD_ID=999${{ env.RUN }}" >> $GITHUB_ENV
          echo "APP_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.RELEASE }}.999${{ env.RUN }}" >> $GITHUB_ENV

      - name: Update version.h
        run: |
          LC_ALL=C ${{ matrix.version_h_modifier }} -e "s@RELEASE 0@RELEASE ${{env.RELEASE}}@g" \
              -e "s@MAJOR 0@MAJOR ${{env.MAJOR}}@g" \
              -e "s@MINOR 0@MINOR ${{env.MINOR}}@g" \
              -e "s@BUILD 0@BUILD ${{ env.BUILD_ID }}@g" \
              src/OSPSuite.FuncParserNative/version.h

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Add OSP NuGet Source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"  --name OSP-GitHub-Packages --username Open-Systems-Pharmacology --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Build Debug and Release
        run: ./buildNix.sh ${{matrix.platform}}  ${{env.APP_VERSION}}

      - name: Push test log as artifact
        uses: actions/upload-artifact@v7
        with:
          name: testLog_${{matrix.os}}
          path: ./**/testLog*.html

  build-nix:
    needs: build-nix-matrix
    if: always()
    runs-on: ${{ vars.GHA_DEFAULT_RUNNER_UBUNTU }}
    steps:
      - name: Aggregate matrix result
        run: ${{ needs.build-nix-matrix.result == 'success' }}

  build-windows-x64:
    runs-on: ${{ vars.GHA_DEFAULT_RUNNER_WINDOWS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: define env variables
        run: |
          echo "BUILD_ID=999${{ env.RUN }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "APP_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.RELEASE }}.999${{ env.RUN }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Add OSP NuGet Source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"  --name OSP-GitHub-Packages --username Open-Systems-Pharmacology --password ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Update version.h
        shell: pwsh
        run: |
          (get-content src\OSPSuite.FuncParserNative\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE ${{env.RELEASE}}" -replace "MAJOR 0", "MAJOR ${{env.MAJOR}}" -replace "MINOR 0", "MINOR ${{env.MINOR}}" -replace "BUILD 0", "BUILD ${{ env.BUILD_ID }}" } | set-content src\OSPSuite.FuncParserNative\version.h

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: build release
        run: msbuild OSPSuite.FuncParser.sln /p:Configuration=Release /p:Platform=x64

      - name: build debug
        run: msbuild OSPSuite.FuncParser.sln /p:Configuration=Debug /p:Platform=x64

      - name: Test
        run: dotnet test --no-build --no-restore --configuration:Release --logger:"html;LogFileName=../../../testLog_Windows.html"

      - name: Pack the project
        run: dotnet pack src/OSPSuite.FuncParser/ -o ./ -p:PackageVersion=${{env.APP_VERSION}}

      - name: Push test log as artifact
        uses: actions/upload-artifact@v7
        with:
          name: testLog_Windows
          path: ./**/testLog*.html
