name: Build and Publish NuGet Package

on:
  push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      # - name: Setup NuGet
      #   run: |
      #     dotnet nuget add source --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore --source https://ci.appveyor.com/nuget/ospsuite-utility --source https://ci.appveyor.com/nuget/ospsuite-bddhelper --source https://www.nuget.org/api/v2/

      - name: Remove Native Project for macOS
        run: dotnet sln OSPSuite.FuncParser.sln remove src/OSPSuite.FuncParserNative/OSPSuite.FuncParserNative.vcxproj

      - name: Build Native Project with CMake (Release)
        run: cmake -BBuild/Release/x64/ -Hsrc/OSPSuite.FuncParserNative/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64
        
      - name: Build the project (Release)
        run: dotnet build OSPSuite.FuncParser.sln --configuration Release


      - name: Test
        run: dotnet test --configuration Release --no-build

      # - name: Pack the project
      #   run: dotnet pack --configuration Release --output ./nupkgs

      # - name: Publish to GitHub Packages
      #   run: dotnet nuget push ./nupkgs/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}