name: Build and Publish NuGet Package

on:
  push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Restore dependencies
        run: dotnet restore --source https://ci.appveyor.com/nuget/ospsuite-utility --source https://ci.appveyor.com/nuget/ospsuite-bddhelper --source https://www.nuget.org/api/v2/

      - name: Remove Native Project for macOS
        run: dotnet sln OSPSuite.FuncParser.sln remove src/OSPSuite.FuncParserNative/OSPSuite.FuncParserNative.vcxproj

      - name: Configure the native build
        run: cmake -BBuild/Release/x64/ -Hsrc/OSPSuite.FuncParserNative/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64
      
      - name: Build native libraries
        run: make -C Build/Release/x64
        
      - name: Build the project
        run: dotnet build OSPSuite.FuncParser.sln --configuration Release


      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack the project
        run: dotnet pack src/OSPSuite.FuncParser/ --configuration Release --output ./nupkgs 

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}